# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RxBZQdQlHMyJ7G1vEJXtFpM47CbIuYQ-
"""

a=int(input("Enter a first number:  "))

b=int(input("Enter a second number:  "))

oper=input("enter a operater:  ")

if oper=="+":
  add=a+b
  print(add)

if oper=="-":
  sub=a-b
  print(sub)

if oper=="/":
  divi=a/b
  print(divi)

if oper=="*":
  multi=a*b
  print(multi)

